import { Inter } from "next/font/google";
import "./globals.css";
import GLobalState from "./context/globalState";
import Nav from "./components/nav";
import RequiredAuth from "./requiredAuth/requiredAuth"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <GLobalState>
        <body className={inter.className}>
          <Nav />
        <RequiredAuth>
          <main>{children}</main>
          <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
        </RequiredAuth>
        </body>
      </GLobalState>
    </html>
  );
}
